---
sidebar: sidebar 
permalink: trident-use/ontap-nas.html 
keywords: trident backend, ontap nas, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: 了解如何使用ONTAP NAS 驱动程序配置ONTAP后端。 
---
= ONTAP NAS 驱动程序概述
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解如何使用ONTAP和Cloud Volumes ONTAP NAS 驱动程序配置ONTAP后端。



== ONTAP NAS 驱动程序详情

Trident提供以下 NAS 存储驱动程序，用于与ONTAP集群通信。支持的访问模式有：_ReadWriteOnce_ (RWO)、_ReadOnlyMany_ (ROX)、_ReadWriteMany_ (RWX)、_ReadWriteOncePod_ (RWOP)。

[cols="2, 1, 1, 2, 2"]
|===
| 驱动程序 | 协议 | 音量模式 | 支持的访问模式 | 支持的文件系统 


| `ontap-nas`  a| 
NFS SMB
 a| 
Filesystem
 a| 
RWO、ROX、RWX、RWOP
 a| 
"， `nfs` ， `smb`



| `ontap-nas-economy`  a| 
NFS SMB
 a| 
Filesystem
 a| 
RWO、ROX、RWX、RWOP
 a| 
"， `nfs` ， `smb`



| `ontap-nas-flexgroup`  a| 
NFS SMB
 a| 
Filesystem
 a| 
RWO、ROX、RWX、RWOP
 a| 
"， `nfs` ， `smb`

|===
[WARNING]
====
* 使用 `ontap-san-economy`仅当预计持续卷使用量高于……时link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["支持的ONTAP容量限制"^]。
* 使用 `ontap-nas-economy`仅当预计持续卷使用量高于……时link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["支持的ONTAP容量限制"^]以及 `ontap-san-economy`驱动程序无法使用。
* 请勿使用 `ontap-nas-economy`如果您预计需要数据保护、灾难恢复或移动办公。
* NetApp不建议在所有ONTAP驱动程序中使用 Flexvol 自动增长，ontap-san 除外。作为一种变通方法， Trident支持使用快照储备，并相应地调整 Flexvol 容量。


====


== 用户权限

Trident预期以ONTAP或 SVM 管理员身份运行，通常使用以下方式： `admin`集群用户或 `vsadmin`SVM 用户，或者具有相同角色但名称不同的用户。

对于Amazon FSx for NetApp ONTAP部署， Trident需要以ONTAP或 SVM 管理员身份运行，并使用集群。 `fsxadmin`用户或 `vsadmin`SVM 用户，或者具有相同角色但名称不同的用户。这 `fsxadmin`用户是集群管理员用户的有限替代品。


NOTE: 如果你使用 `limitAggregateUsage`需要参数和集群管理员权限。当使用Amazon FSx for NetApp ONTAP和Trident时， `limitAggregateUsage`参数将无法与 `vsadmin`和 `fsxadmin`用户账户。如果指定此参数，配置操作将失败。

虽然可以在ONTAP中创建一个Trident驱动程序可以使用的限制性更强的角色，但我们不建议这样做。  Trident的大多数新版本都会调用额外的 API，这些 API 必须加以考虑，这使得升级变得困难且容易出错。
