---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: '通过将Trident与Amazon FSx for NetApp ONTAP结合使用，您可以确保在 Amazon Elastic Kubernetes Service (EKS) 中运行的 Kubernetes 集群可以配置由ONTAP支持的块和文件持久卷。' 
---
= 安装Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident简化了 Kubernetes 中Amazon FSx for NetApp ONTAP存储管理，使您的开发人员和管理员能够专注于应用程序部署。

您可以使用以下方法之一安装Trident ：

* 舵
* EKS 附加组件


如果要使用快照功能，请安装 CSI 快照控制器插件。请参阅link:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["为CSI卷启用快照功能"^]了解更多信息。



== 通过 Helm 安装Trident。

[role="tabbed-block"]
====
.Pod 身份
--
. 添加Trident Helm 仓库：
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 请按照以下示例安装Trident ：
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace
----
+
您可以使用 `helm list`查看安装详细信息的命令，例如名称、命名空间、图表、状态、应用程序版本和修订号。

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----


--
.服务账户协会（IRSA）
--
. 添加Trident Helm 仓库：
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 设置*云提供商*和*云身份*的值：
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1  \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
您可以使用 `helm list`查看安装详细信息的命令，例如名称、命名空间、图表、状态、应用程序版本和修订号。

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2506.0    25.06.0
----


--
====
[NOTE]
====
如果您计划使用 iSCSI，请确保您的客户端计算机上已启用 iSCSI。如果您使用的是 AL2023 工作节点操作系统，可以通过在 Helm 安装中添加节点准备参数来自动安装 iSCSI 客户端：

[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace –-set nodePrep={iscsi}
----
====


== 通过 EKS 插件安装Trident

Trident EKS 插件包含最新的安全补丁和错误修复，并经过 AWS 验证，可与 Amazon EKS 配合使用。  EKS 插件使您能够持续确保您的 Amazon EKS 集群安全稳定，并减少安装、配置和更新插件所需的工作量。



=== 前提条件

在为 AWS EKS 配置Trident插件之前，请确保您已具备以下条件：

* 带有附加订阅的 Amazon EKS 集群帐户
* AWS 对 AWS Marketplace 的权限：
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* AMI 类型：Amazon Linux 2 (AL2_x86_64) 或 Amazon Linux 2 Arm (AL2_ARM_64)
* 节点类型：AMD 或ARM
* 现有的Amazon FSx for NetApp ONTAP文件系统




=== 启用适用于 AWS 的Trident插件

[role="tabbed-block"]
====
.管理控制台
--
. 打开 Amazon EKS 控制台 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左侧导航窗格中，选择“集群”。
. 选择要为其配置NetApp Trident CSI 插件的集群名称。
. 选择“附加组件”，然后选择“获取更多附加组件”。
. 请按照以下步骤选择插件：
+
.. 向下滚动到“AWS Marketplace 附加组件”部分，然后在搜索框中输入“Trident”。
.. 选中“Trident by NetApp”框右上角的复选框。
.. 选择“下一步”。


. 在“配置所选插件”设置页面上，执行以下操作：
+

NOTE: *如果您使用 Pod Identity 关联，请跳过这些步骤。*

+
.. 请选择您要使用的*版本*。
.. 如果您使用IRSA身份验证，请确保设置可选配置设置中提供的配置值：
+
*** 请选择您要使用的*版本*。
*** 按照*附加组件配置方案*进行操作，并将*配置值*部分中的*configurationValues*参数设置为您在上一步创建的角色 ARN（值应采用以下格式）：




+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
  "cloudProvider": "AWS"

}
----
+
如果选择“覆盖”作为冲突解决方法，则现有插件的一个或多个设置可能会被 Amazon EKS 插件设置覆盖。如果您不启用此选项，并且与您现有的设置存在冲突，则操作将失败。您可以使用生成的错误信息来排查冲突问题。在选择此选项之前，请确保 Amazon EKS 插件不会管理您需要自行管理的设置。

. 选择“下一步”。
. 在“审核和添加”页面上，选择“创建”。
+
插件安装完成后，您将看到已安装的插件。



--
.AWS CLI
--
*1.创建 `add-on.json`文件*：

*对于 Pod 标识，请使用以下格式*：

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
}
----
*对于IRSA认证，请使用以下格式*：

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----

NOTE: 代替 `<role ARN>`使用上一步创建的角色的 ARN。

*2.安装Trident EKS 插件。*

[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----
--
.eksctl
--
以下示例命令安装Trident EKS 插件：

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> --force
----
--
====


=== 更新Trident EKS 插件

[role="tabbed-block"]
====
.管理控制台
--
. 打开 Amazon EKS 控制台 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左侧导航窗格中，选择“集群”。
. 选择要为其更新NetApp Trident CSI 插件的集群名称。
. 选择“附加组件”选项卡。
. 选择“ NetApp Trident ”，然后选择“编辑”。
. 在“配置NetApp Trident ”页面上，执行以下操作：
+
.. 请选择您要使用的*版本*。
.. 展开“可选配置设置”，并根据需要进行修改。
.. 选择“保存更改”。




--
.AWS CLI
--
以下示例更新 EKS 插件：

[source, console]
----
aws eks update-addon --cluster-name <eks_cluster_name> --addon-name netapp_trident-operator --addon-version v25.6.0-eksbuild.1 \
  --service-account-role-arn <role-ARN> --resolve-conflict preserve \
  --configuration-values “{\"cloudIdentity\": \"'eks.amazonaws.com/role-arn: <role ARN>'\"}"
----
--
.eksctl
--
* 请检查您的 FSxN Trident CSI 插件的当前版本。代替 `my-cluster`使用您的集群名称。
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*示例输出：*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.6.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* 将插件更新到上一步输出中“UPDATE AVAILABLE”下返回的版本。
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.6.0-eksbuild.1 --cluster my-cluster --force
----


如果你移除 `--force`如果选项和任何 Amazon EKS 插件设置与您现有的设置冲突，则更新 Amazon EKS 插件将失败；您将收到一条错误消息，以帮助您解决冲突。在指定此选项之前，请确保 Amazon EKS 插件不会管理您需要管理的设置，因为此选项会覆盖这些设置。有关此设置的其他选项的更多信息，请参阅link:https://eksctl.io/usage/addons/["插件"]。有关 Amazon EKS Kubernetes 字段管理的更多信息，请参阅link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Kubernetes 字段管理"]。

--
====


=== 卸载/移除Trident EKS 插件

您可以通过两种方式移除 Amazon EKS 插件：

* *保留集群上的附加软件* – 此选项移除 Amazon EKS 对所有设置的管理。它还取消了 Amazon EKS 通知您更新以及在您启动更新后自动更新 Amazon EKS 插件的功能。但是，它可以保留集群上的附加软件。此选项使插件成为自管理安装，而不是 Amazon EKS 插件。选择此选项，插件不会出现停机时间。保留 `--preserve`命令中的选项用于保留插件。
* *从集群中完全移除附加软件* – NetApp建议，仅当集群中没有任何资源依赖于 Amazon EKS 附加组件时，才从集群中移除该附加组件。移除 `--preserve`选项 `delete`移除插件的命令。



NOTE: 如果插件关联了 IAM 帐户，则不会删除该 IAM 帐户。

[role="tabbed-block"]
====
.管理控制台
--
. 打开 Amazon EKS 控制台 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左侧导航窗格中，选择“集群”。
. 选择要从中移除NetApp Trident CSI 插件的集群名称。
. 选择“附加组件”选项卡，然后选择“ NetApp Trident ”。
. 选择*删除*。
. 在“移除 netapp_trident-operator 确认”对话框中，执行以下操作：
+
.. 如果您希望 Amazon EKS 停止管理插件的设置，请选择“在集群上保留”。如果您希望在集群上保留附加软件，以便您可以自行管理附加软件的所有设置，请执行此操作。
.. 输入 *netapp_trident-operator*。
.. 选择*删除*。




--
.AWS CLI
--
代替 `my-cluster`输入集群名称，然后运行以下命令。

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
.eksctl
--
以下命令卸载Trident EKS 插件：

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
====