---
sidebar: sidebar 
permalink: trident-concepts/snapshots.html 
keywords: provisioning, Trident 
summary: 了解更多关于Trident如何处理其驱动程序的卷快照创建的信息。 
---
= 卷快照
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解更多关于Trident如何处理其驱动程序的卷快照创建的信息。



== 了解如何创建卷快照

* 对于 `ontap-nas`， `ontap-san` ， `gcp-cvs` ， 和 `azure-netapp-files`驱动程序中，每个持久卷 (PV) 都映射到一个FlexVol volume。因此，卷快照被创建为NetApp快照。 NetApp快照技术比同类快照技术具有更高的稳定性、可扩展性、可恢复性和性能。这些快照副本在创建所需时间和存储空间方面都非常高效。
* 对于 `ontap-nas-flexgroup`驱动程序中，每个持久卷 (PV) 都映射到一个FlexGroup。因此，卷快照将创建为NetApp FlexGroup快照。 NetApp快照技术比同类快照技术具有更高的稳定性、可扩展性、可恢复性和性能。这些快照副本在创建所需时间和存储空间方面都非常高效。
* 对于 `ontap-san-economy`驱动程序，PV 映射到在共享FlexVol卷上创建的 LUN。通过对关联的 LUN 执行 FlexClone 操作，即可获得 PV 的 VolumeSnapshot。 ONTAP FlexClone技术能够几乎瞬间创建即使是最大数据集的副本。副本与其父级共享数据块，除了元数据所需的空间外，不占用任何存储空间。
* 对于 `solidfire-san`驱动程序中，每个 PV 映射到在NetApp Element软件/ NetApp HCI集群上创建的 LUN。 VolumeSnapshots 由底层 LUN 的 Element 快照表示。这些快照是特定时间点的副本，仅占用少量系统资源和空间。
* 当与 `ontap-nas`和 `ontap-san`驱动程序中， ONTAP快照是FlexVol的某个时间点的副本，会占用FlexVol本身的空间。随着快照的创建/计划，这会导致卷中的可写空间随时间减少。解决此问题的一个简单方法是通过 Kubernetes 调整大小来增加卷。另一种方法是删除不再需要的快照。当通过 Kubernetes 创建的 VolumeSnapshot 被删除时， Trident将删除关联的ONTAP快照。并非通过 Kubernetes 创建的ONTAP快照也可以删除。


使用Trident，您可以利用 VolumeSnapshots 从中创建新的 PV。使用FlexClone技术从这些快照创建 PV，适用于受支持的ONTAP和 CVS 后端。从快照创建 PV 时，后备卷是快照父卷的FlexClone 。这 `solidfire-san`驱动程序使用 Element 软件卷克隆从快照创建 PV。它在这里从 Element 快照创建一个克隆。
