---
sidebar: sidebar 
permalink: trident-reference/rest-api.html 
keywords: rest api, get, post, json, object, backends 
summary: 如果您更喜欢与 Trident 的 REST API 进行交互，可以直接使用 REST 端点。 
---
= Trident REST API
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
尽管link:tridentctl.html["tridentctl 命令和选项"]这是与Trident REST API 交互的最简单方法，如果您愿意，也可以直接使用 REST 端点。



== 何时使用 REST API

REST API 适用于在非 Kubernetes 部署中使用Trident作为独立二进制文件的高级安装。

为了更好的安全性，Trident `REST API`在 pod 内运行时，默认仅限于 localhost。要改变这种行为，你需要设置 Trident 的 `-address`在其 pod 配置中设置参数。



== 使用 REST API

要查看这些 API 的调用示例，请传递调试信息。(`-d` ） 旗帜。更多信息，请参阅link:../trident-managing-k8s/tridentctl.html["使用 tridentctl 管理Trident"]。

API 的工作原理如下：



=== GET

`GET <trident-address>/trident/v1/<object-type>`:: 列出该类型的所有对象。
`GET <trident-address>/trident/v1/<object-type>/<object-name>`:: 获取指定对象的详细信息。




=== POST

`POST <trident-address>/trident/v1/<object-type>`:: 创建指定类型的对象。
+
--
* 创建对象需要 JSON 配置。有关每种对象类型的详细说明，请参阅：link:../trident-managing-k8s/tridentctl.html["使用 tridentctl 管理Trident"] 。
* 如果对象已存在，则行为会有所不同：后端会更新现有对象，而所有其他对象类型都会使操作失败。


--




=== DELETE

`DELETE <trident-address>/trident/v1/<object-type>/<object-name>`:: 删除指定的资源。
+
--

NOTE: 与后端或存储类关联的卷将继续存在；这些卷必须单独删除。更多信息，请参阅link:../trident-managing-k8s/tridentctl.html["使用 tridentctl 管理Trident"]。

--

